### ISSUE TITLE
Please remove stale *.pro files

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/deepin-camera#3]
The project currently doesn't build with qmake, since `config.h` is expected to be generated from `config.h.in` by cmake. Please remove the stale qmake *.pro files.

**Comment by BLumia** [comment]
I saw there was a commit https://github.com/linuxdeepin/deepin-camera/commit/26d034e44f2ce86e5c8b5a00154363a98a2215ca to address this issue (to make project buildable via qmake). I guess we can close this now :joy:
